(define (problem drone_problem_d1_r0_l25_p25_c25_g25_ct2)
(:domain project1_domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
)
(:init
	(at-drone drone1 depot)
	(free-arm1 drone1)
	(free-arm2 drone1)
	(at-crate crate1 depot)
	(at-crate crate2 depot)
	(at-crate crate3 depot)
	(at-crate crate4 depot)
	(at-crate crate5 depot)
	(at-crate crate6 depot)
	(at-crate crate7 depot)
	(at-crate crate8 depot)
	(at-crate crate9 depot)
	(at-crate crate10 depot)
	(at-crate crate11 depot)
	(at-crate crate12 depot)
	(at-crate crate13 depot)
	(at-crate crate14 depot)
	(at-crate crate15 depot)
	(at-crate crate16 depot)
	(at-crate crate17 depot)
	(at-crate crate18 depot)
	(at-crate crate19 depot)
	(at-crate crate20 depot)
	(at-crate crate21 depot)
	(at-crate crate22 depot)
	(at-crate crate23 depot)
	(at-crate crate24 depot)
	(at-crate crate25 depot)
	(has-content crate1 food)
	(has-content crate2 food)
	(has-content crate3 food)
	(has-content crate4 food)
	(has-content crate5 food)
	(has-content crate6 food)
	(has-content crate7 food)
	(has-content crate8 food)
	(has-content crate9 food)
	(has-content crate10 food)
	(has-content crate11 food)
	(has-content crate12 food)
	(has-content crate13 food)
	(has-content crate14 food)
	(has-content crate15 food)
	(has-content crate16 food)
	(has-content crate17 food)
	(has-content crate18 food)
	(has-content crate19 food)
	(has-content crate20 medicine)
	(has-content crate21 medicine)
	(has-content crate22 medicine)
	(has-content crate23 medicine)
	(has-content crate24 medicine)
	(has-content crate25 medicine)
	(at-person person1 loc1)
	(at-person person2 loc16)
	(at-person person3 loc16)
	(at-person person4 loc4)
	(at-person person5 loc25)
	(at-person person6 loc8)
	(at-person person7 loc9)
	(at-person person8 loc7)
	(at-person person9 loc17)
	(at-person person10 loc1)
	(at-person person11 loc5)
	(at-person person12 loc22)
	(at-person person13 loc4)
	(at-person person14 loc24)
	(at-person person15 loc12)
	(at-person person16 loc23)
	(at-person person17 loc23)
	(at-person person18 loc8)
	(at-person person19 loc21)
	(at-person person20 loc3)
	(at-person person21 loc20)
	(at-person person22 loc5)
	(at-person person23 loc21)
	(at-person person24 loc19)
	(at-person person25 loc24)
)
(:goal (and
	(at-drone drone1 depot)
	(delivered person1 food)
	(delivered person2 food)
	(delivered person4 food)
	(delivered person5 food)
	(delivered person6 food)
	(delivered person7 food)
	(delivered person9 food)
	(delivered person10 food)
	(delivered person10 medicine)
	(delivered person11 food)
	(delivered person12 food)
	(delivered person12 medicine)
	(delivered person13 food)
	(delivered person14 food)
	(delivered person15 food)
	(delivered person16 food)
	(delivered person17 food)
	(delivered person17 medicine)
	(delivered person18 medicine)
	(delivered person19 food)
	(delivered person20 food)
	(delivered person23 food)
	(delivered person24 medicine)
	(delivered person25 food)
	(delivered person25 medicine)
	))
)
