(define (problem drone_problem_d1_r0_l48_p48_c48_g48_ct2)
(:domain project1_domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
)
(:init
	(at-drone drone1 depot)
	(free-arm1 drone1)
	(free-arm2 drone1)
	(at-crate crate1 depot)
	(at-crate crate2 depot)
	(at-crate crate3 depot)
	(at-crate crate4 depot)
	(at-crate crate5 depot)
	(at-crate crate6 depot)
	(at-crate crate7 depot)
	(at-crate crate8 depot)
	(at-crate crate9 depot)
	(at-crate crate10 depot)
	(at-crate crate11 depot)
	(at-crate crate12 depot)
	(at-crate crate13 depot)
	(at-crate crate14 depot)
	(at-crate crate15 depot)
	(at-crate crate16 depot)
	(at-crate crate17 depot)
	(at-crate crate18 depot)
	(at-crate crate19 depot)
	(at-crate crate20 depot)
	(at-crate crate21 depot)
	(at-crate crate22 depot)
	(at-crate crate23 depot)
	(at-crate crate24 depot)
	(at-crate crate25 depot)
	(at-crate crate26 depot)
	(at-crate crate27 depot)
	(at-crate crate28 depot)
	(at-crate crate29 depot)
	(at-crate crate30 depot)
	(at-crate crate31 depot)
	(at-crate crate32 depot)
	(at-crate crate33 depot)
	(at-crate crate34 depot)
	(at-crate crate35 depot)
	(at-crate crate36 depot)
	(at-crate crate37 depot)
	(at-crate crate38 depot)
	(at-crate crate39 depot)
	(at-crate crate40 depot)
	(at-crate crate41 depot)
	(at-crate crate42 depot)
	(at-crate crate43 depot)
	(at-crate crate44 depot)
	(at-crate crate45 depot)
	(at-crate crate46 depot)
	(at-crate crate47 depot)
	(at-crate crate48 depot)
	(has-content crate1 food)
	(has-content crate2 food)
	(has-content crate3 food)
	(has-content crate4 food)
	(has-content crate5 food)
	(has-content crate6 food)
	(has-content crate7 food)
	(has-content crate8 food)
	(has-content crate9 food)
	(has-content crate10 food)
	(has-content crate11 food)
	(has-content crate12 food)
	(has-content crate13 food)
	(has-content crate14 food)
	(has-content crate15 food)
	(has-content crate16 food)
	(has-content crate17 food)
	(has-content crate18 food)
	(has-content crate19 food)
	(has-content crate20 food)
	(has-content crate21 food)
	(has-content crate22 food)
	(has-content crate23 food)
	(has-content crate24 food)
	(has-content crate25 food)
	(has-content crate26 food)
	(has-content crate27 medicine)
	(has-content crate28 medicine)
	(has-content crate29 medicine)
	(has-content crate30 medicine)
	(has-content crate31 medicine)
	(has-content crate32 medicine)
	(has-content crate33 medicine)
	(has-content crate34 medicine)
	(has-content crate35 medicine)
	(has-content crate36 medicine)
	(has-content crate37 medicine)
	(has-content crate38 medicine)
	(has-content crate39 medicine)
	(has-content crate40 medicine)
	(has-content crate41 medicine)
	(has-content crate42 medicine)
	(has-content crate43 medicine)
	(has-content crate44 medicine)
	(has-content crate45 medicine)
	(has-content crate46 medicine)
	(has-content crate47 medicine)
	(has-content crate48 medicine)
	(at-person person1 loc19)
	(at-person person2 loc16)
	(at-person person3 loc2)
	(at-person person4 loc48)
	(at-person person5 loc11)
	(at-person person6 loc21)
	(at-person person7 loc22)
	(at-person person8 loc47)
	(at-person person9 loc27)
	(at-person person10 loc3)
	(at-person person11 loc37)
	(at-person person12 loc16)
	(at-person person13 loc19)
	(at-person person14 loc29)
	(at-person person15 loc9)
	(at-person person16 loc20)
	(at-person person17 loc8)
	(at-person person18 loc23)
	(at-person person19 loc8)
	(at-person person20 loc25)
	(at-person person21 loc27)
	(at-person person22 loc27)
	(at-person person23 loc32)
	(at-person person24 loc28)
	(at-person person25 loc16)
	(at-person person26 loc37)
	(at-person person27 loc35)
	(at-person person28 loc4)
	(at-person person29 loc12)
	(at-person person30 loc13)
	(at-person person31 loc40)
	(at-person person32 loc14)
	(at-person person33 loc37)
	(at-person person34 loc47)
	(at-person person35 loc1)
	(at-person person36 loc16)
	(at-person person37 loc22)
	(at-person person38 loc48)
	(at-person person39 loc9)
	(at-person person40 loc14)
	(at-person person41 loc5)
	(at-person person42 loc1)
	(at-person person43 loc20)
	(at-person person44 loc23)
	(at-person person45 loc7)
	(at-person person46 loc21)
	(at-person person47 loc15)
	(at-person person48 loc18)
)
(:goal (and
	(at-drone drone1 depot)
	(delivered person1 food)
	(delivered person2 food)
	(delivered person3 food)
	(delivered person5 medicine)
	(delivered person6 food)
	(delivered person8 food)
	(delivered person10 food)
	(delivered person11 medicine)
	(delivered person13 medicine)
	(delivered person14 food)
	(delivered person14 medicine)
	(delivered person15 food)
	(delivered person15 medicine)
	(delivered person16 food)
	(delivered person16 medicine)
	(delivered person17 medicine)
	(delivered person19 food)
	(delivered person20 food)
	(delivered person22 medicine)
	(delivered person25 food)
	(delivered person25 medicine)
	(delivered person26 medicine)
	(delivered person27 medicine)
	(delivered person28 food)
	(delivered person28 medicine)
	(delivered person29 medicine)
	(delivered person31 medicine)
	(delivered person32 food)
	(delivered person32 medicine)
	(delivered person33 food)
	(delivered person33 medicine)
	(delivered person34 food)
	(delivered person35 food)
	(delivered person35 medicine)
	(delivered person36 food)
	(delivered person36 medicine)
	(delivered person37 food)
	(delivered person39 food)
	(delivered person39 medicine)
	(delivered person40 food)
	(delivered person40 medicine)
	(delivered person43 food)
	(delivered person43 medicine)
	(delivered person44 food)
	(delivered person45 food)
	(delivered person46 food)
	(delivered person48 food)
	(delivered person48 medicine)
	))
)
